spring:
  #  profiles:
  #    active:
  output:
    ansi:
      enabled: always
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://t2.yejin.site:3306/mybatis_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: yejin
    password: yejin1234
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    com.ll.exam : DEBUG
    # springframework: DEBUG
